// <copyright file="CommonEnums.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (rebuild this project).
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUnique.OpenMU.Network.Packets;

using System;
using static System.Buffers.Binary.BinaryPrimitives;    /// <summary>
    /// Defines from or to which item storage an item is moved.
    /// </summary>
    public enum ItemStorageKind
    {
        /// <summary>
        /// The inventory storage.
        /// </summary>
            Inventory = 0,

        /// <summary>
        /// The trade storage.
        /// </summary>
            Trade = 1,

        /// <summary>
        /// The vault storage.
        /// </summary>
            Vault = 2,

        /// <summary>
        /// The chaos machine storage.
        /// </summary>
            ChaosMachine = 3,

        /// <summary>
        /// The player shop storage.
        /// </summary>
            PlayerShop = 4,

        /// <summary>
        /// The pet trainer dialog storage.
        /// </summary>
            PetTrainer = 5,

        /// <summary>
        /// The storage of the refinery of the elphis npc.
        /// </summary>
            Refinery = 6,

        /// <summary>
        /// The storage of the smelting dialog of the osbourne npc.
        /// </summary>
            Smelting = 7,

        /// <summary>
        /// The storage of the item restore dialog of the jerridon npc.
        /// </summary>
            ItemRestore = 8,

        /// <summary>
        /// The storage of the chaos card master dialog.
        /// </summary>
            ChaosCardMaster = 9,

        /// <summary>
        /// The storage of the cherry blossom spirit dialog.
        /// </summary>
            CherryBlossomSpirit = 10,

        /// <summary>
        /// The storage of the seed crafting dialog.
        /// </summary>
            SeedCrafting = 11,

        /// <summary>
        /// The storage of the seed sphere crafting dialog.
        /// </summary>
            SeedSphereCrafting = 12,

        /// <summary>
        /// The storage of the seed sphere mount dialog.
        /// </summary>
            SeedMountCrafting = 13,

        /// <summary>
        /// The storage of the seed sphere unmount dialog.
        /// </summary>
            SeedUnmountCrafting = 14,
    }

    /// <summary>
    /// The quest state for the legacy quest system.
    /// </summary>
    public enum LegacyQuestState
    {
        /// <summary>
        /// The state is undefined. This value is used when there is no quest defined for a specific index
        /// </summary>
            Undefined = 0,

        /// <summary>
        /// The quest is active and in progress.
        /// </summary>
            Active = 1,

        /// <summary>
        /// The quest was completed.
        /// </summary>
            Complete = 2,

        /// <summary>
        /// The quest is inactive, that means it isn't active and wasn't completed yet.
        /// </summary>
            Inactive = 3,
    }

    /// <summary>
    /// Defines the values which are used for the character classes on client side.
    /// </summary>
    public enum CharacterClassNumber
    {
        /// <summary>
        /// Value for the dark wizard character class.
        /// </summary>
            DarkWizard = 0,

        /// <summary>
        /// Value for the soul master character class.
        /// </summary>
            SoulMaster = 2,

        /// <summary>
        /// Value for the grand master character class.
        /// </summary>
            GrandMaster = 3,

        /// <summary>
        /// Value for the dark knight character class.
        /// </summary>
            DarkKnight = 4,

        /// <summary>
        /// Value for the blade knight character class.
        /// </summary>
            BladeKnight = 6,

        /// <summary>
        /// Value for the blade master character class.
        /// </summary>
            BladeMaster = 7,

        /// <summary>
        /// Value for the fairy elf character class.
        /// </summary>
            FairyElf = 8,

        /// <summary>
        /// Value for the muse elf character class.
        /// </summary>
            MuseElf = 10,

        /// <summary>
        /// Value for the high elf character class.
        /// </summary>
            HighElf = 11,

        /// <summary>
        /// Value for the magic gladiator character class.
        /// </summary>
            MagicGladiator = 12,

        /// <summary>
        /// Value for the duel master character class.
        /// </summary>
            DuelMaster = 13,

        /// <summary>
        /// Value for the dark lord character class.
        /// </summary>
            DarkLord = 16,

        /// <summary>
        /// Value for the lord emperor character class.
        /// </summary>
            LordEmperor = 17,

        /// <summary>
        /// Value for the summoner character class.
        /// </summary>
            Summoner = 20,

        /// <summary>
        /// Value for the bloody summoner character class.
        /// </summary>
            BloodySummoner = 22,

        /// <summary>
        /// Value for the dimension master character class.
        /// </summary>
            DimensionMaster = 23,

        /// <summary>
        /// Value for the rage fighter character class.
        /// </summary>
            RageFighter = 24,

        /// <summary>
        /// Value for the fist master character class.
        /// </summary>
            FistMaster = 25,
    }

    /// <summary>
    /// Defines the values which are used for the character classes on client side.
    /// </summary>
    public enum CharacterClassNumberS21
    {
        /// <summary>
        /// Value for the dark wizard character class. Bits: 0b0000_0000_0000
        /// </summary>
            DarkWizard = 0,

        /// <summary>
        /// Value for the soul master character class. Bits: 0b0000_0000_1000
        /// </summary>
            SoulMaster = 8,

        /// <summary>
        /// Value for the grand master character class. Bits: 0b0000_0000_1100
        /// </summary>
            GrandMaster = 12,

        /// <summary>
        /// Value for the soul wizard advanced class. Bits: 0b0000_0000_1110
        /// </summary>
            SoulWizard = 14,

        /// <summary>
        /// Value for the darkness wizard advanced class. Bits: 0b0000_0000_1111
        /// </summary>
            DarknessWizard = 15,

        /// <summary>
        /// Value for the dark knight character class. Bits: 0b0000_0001_0000
        /// </summary>
            DarkKnight = 16,

        /// <summary>
        /// Value for the blade knight character class. Bits: 0b0000_0001_1000
        /// </summary>
            BladeKnight = 24,

        /// <summary>
        /// Value for the blade master advanced class. Bits: 0b0000_0001_1100
        /// </summary>
            BladeMaster = 28,

        /// <summary>
        /// Value for the dragon knight advanced class. Bits: 0b0000_0001_1110
        /// </summary>
            DragonKnight = 30,

        /// <summary>
        /// Value for the ignition knight ultimate class. Bits: 0b0000_0001_1111
        /// </summary>
            IgnitionKnight = 31,

        /// <summary>
        /// Value for the fairy elf character class. Bits: 0b0000_0010_0000
        /// </summary>
            FairyElf = 32,

        /// <summary>
        /// Value for the muse elf character class. Bits: 0b0000_0010_1000
        /// </summary>
            MuseElf = 40,

        /// <summary>
        /// Value for the high elf advanced class. Bits: 0b0000_0010_1100
        /// </summary>
            HighElf = 44,

        /// <summary>
        /// Value for the noble elf advanced class. Bits: 0b0000_0010_1110
        /// </summary>
            NobleElf = 46,

        /// <summary>
        /// Value for the royal elf ultimate class. Bits: 0b0000_0010_1111
        /// </summary>
            RoyalElf = 47,

        /// <summary>
        /// Value for the magic gladiator character class. Bits: 0b0000_0011_0000
        /// </summary>
            MagicGladiator = 48,

        /// <summary>
        /// Value for the duel master advanced class. Bits: 0b0000_0011_1100
        /// </summary>
            DuelMaster = 60,

        /// <summary>
        /// Value for the magic knight advanced class. Bits: 0b0000_0011_1110
        /// </summary>
            MagicKnight = 62,

        /// <summary>
        /// Value for the duple knight ultimate class. Bits: 0b0000_0011_1111
        /// </summary>
            DupleKnight = 63,

        /// <summary>
        /// Value for the dark lord character class. Bits: 0b0000_0100_0000
        /// </summary>
            DarkLord = 64,

        /// <summary>
        /// Value for the lord emperor advanced class. Bits: 0b0000_0100_1100
        /// </summary>
            LordEmperor = 76,

        /// <summary>
        /// Value for the empire lord advanced class. Bits: 0b0000_0100_1110
        /// </summary>
            EmpireLord = 78,

        /// <summary>
        /// Value for the force empire ultimate class. Bits: 0b0000_0100_1111
        /// </summary>
            ForceEmpire = 79,

        /// <summary>
        /// Value for the summoner character class. Bits: 0b0000_0101_0000
        /// </summary>
            Summoner = 80,

        /// <summary>
        /// Value for the bloody summoner advanced class. Bits: 0b0000_0101_1000
        /// </summary>
            BloodySummoner = 88,

        /// <summary>
        /// Value for the dimension master advanced class. Bits: 0b0000_0101_1100
        /// </summary>
            DimensionMaster = 92,

        /// <summary>
        /// Value for the dimension summoner elite class. Bits: 0b0000_0101_1110
        /// </summary>
            DimensionSummoner = 94,

        /// <summary>
        /// Value for the endless summoner ultimate class. Bits: 0b0000_0101_1111
        /// </summary>
            EndlessSummoner = 95,

        /// <summary>
        /// Value for the rage fighter character class. Bits: 0b0000_0110_0000
        /// </summary>
            RageFighter = 96,

        /// <summary>
        /// Value for the fist master advanced class. Bits: 0b0000_0110_1100
        /// </summary>
            FistMaster = 108,

        /// <summary>
        /// Value for the fist blazer elite class. Bits: 0b0000_0110_1110
        /// </summary>
            FistBlazer = 110,

        /// <summary>
        /// Value for the bloody fighter ultimate class. Bits: 0b0000_0110_1111
        /// </summary>
            BloodyFighter = 111,

        /// <summary>
        /// Value for the grow lancer character class. Bits: 0b0000_0111_0000
        /// </summary>
            GrowLancer = 112,

        /// <summary>
        /// Value for the mirage lancer advanced class. Bits: 0b0000_0111_1100
        /// </summary>
            MirageLancer = 124,

        /// <summary>
        /// Value for the shining lancer elite class. Bits: 0b0000_0111_1110
        /// </summary>
            ShiningLancer = 126,

        /// <summary>
        /// Value for the arcane lancer ultimate class. Bits: 0b0000_0111_1111
        /// </summary>
            ArcaneLancer = 127,

        /// <summary>
        /// Value for the rune wizard character class. Bits: 0b0000_1000_0000
        /// </summary>
            RuneWizard = 128,

        /// <summary>
        /// Value for the rune spell master advanced class. Bits: 0b0000_1000_1000
        /// </summary>
            RuneSpellMaster = 136,

        /// <summary>
        /// Value for the grand rune master advanced class. Bits: 0b0000_1000_1100
        /// </summary>
            GrandRuneMaster = 140,

        /// <summary>
        /// Value for the majestic rune wizard elite class. Bits: 0b0000_1000_1110
        /// </summary>
            MajesticRuneWizard = 142,

        /// <summary>
        /// Value for the infinity rune wizard ultimate class. Bits: 0b0000_1000_1111
        /// </summary>
            InfinityRuneWizard = 143,

        /// <summary>
        /// Value for the slayer character class. Bits: 0b0000_1001_0000
        /// </summary>
            Slayer = 144,

        /// <summary>
        /// Value for the royal slayer advanced class. Bits: 0b0000_1001_1000
        /// </summary>
            RoyalSlayer = 152,

        /// <summary>
        /// Value for the master slayer advanced class. Bits: 0b0000_1001_1100
        /// </summary>
            MasterSlayer = 156,

        /// <summary>
        /// Value for the slaughterer elite class. Bits: 0b0000_1001_1110
        /// </summary>
            Slaughterer = 158,

        /// <summary>
        /// Value for the rogue slayer ultimate class. Bits: 0b0000_1001_1111
        /// </summary>
            RogueSlayer = 159,

        /// <summary>
        /// Value for the gun crusher character class. Bits: 0b0000_1010_0000
        /// </summary>
            GunCrusher = 160,

        /// <summary>
        /// Value for the gun breaker advanced class. Bits: 0b0000_1010_1000
        /// </summary>
            GunBreaker = 168,

        /// <summary>
        /// Value for the master gun breaker advanced class. Bits: 0b0000_1010_1100
        /// </summary>
            MasterGunBreaker = 172,

        /// <summary>
        /// Value for the heist gun crusher elite class. Bits: 0b0000_1010_1110
        /// </summary>
            HeistGunCrusher = 174,

        /// <summary>
        /// Value for the magnus gun crusher ultimate class. Bits: 0b0000_1010_1111
        /// </summary>
            MagnusGunCrusher = 175,

        /// <summary>
        /// Value for the white wizard character class. Bits: 0b0000_1011_0000
        /// </summary>
            WhiteWizard = 176,

        /// <summary>
        /// Value for the light master advanced class. Bits: 0b0000_1011_1000
        /// </summary>
            LightMaster = 184,

        /// <summary>
        /// Value for the shine wizard advanced class. Bits: 0b0000_1011_1100
        /// </summary>
            ShineWizard = 188,

        /// <summary>
        /// Value for the luminous wizard elite class. Bits: 0b0000_1011_1110
        /// </summary>
            LuminousWizard = 190,

        /// <summary>
        /// Value for the glory wizard ultimate class. Bits: 0b0000_1011_1111
        /// </summary>
            GloryWizard = 191,

        /// <summary>
        /// Value for the lemuria character class. Bits: 0b0000_1100_0000
        /// </summary>
            Lemuria = 192,

        /// <summary>
        /// Value for the wo mage advanced class. Bits: 0b0000_1100_1000
        /// </summary>
            WoMage = 200,

        /// <summary>
        /// Value for the arch mage advanced class. Bits: 0b0000_1100_1100
        /// </summary>
            ArchMage = 204,

        /// <summary>
        /// Value for the mystic mage elite class. Bits: 0b0000_1100_1110
        /// </summary>
            MysticMage = 206,

        /// <summary>
        /// Value for the battle mage ultimate class. Bits: 0b0000_1100_1111
        /// </summary>
            BattleMage = 207,

        /// <summary>
        /// Value for the illusion knight character class. Bits: 0b0000_1101_0000
        /// </summary>
            IllusionKnight = 208,

        /// <summary>
        /// Value for the mirage knight advanced class. Bits: 0b0000_1101_1000
        /// </summary>
            MirageKnight = 216,

        /// <summary>
        /// Value for the illusion master advanced class. Bits: 0b0000_1101_1100
        /// </summary>
            IllusionMaster = 220,

        /// <summary>
        /// Value for the mystic knight elite class. Bits: 0b0000_1101_1110
        /// </summary>
            MysticKnight = 222,

        /// <summary>
        /// Value for the phantom pain knight ultimate class. Bits: 0b0000_1101_1111
        /// </summary>
            PhantomPainKnight = 223,

        /// <summary>
        /// Value for the alchemist character class. Bits: 0b0000_1110_0000
        /// </summary>
            Alchemist = 224,

        /// <summary>
        /// Value for the alchemic magician advanced class. Bits: 0b0000_1110_1000
        /// </summary>
            AlchemicMagician = 232,

        /// <summary>
        /// Value for the alchemic master advanced class. Bits: 0b0000_1110_1100
        /// </summary>
            AlchemicMaster = 236,

        /// <summary>
        /// Value for the alchemic force elite class. Bits: 0b0000_1110_1110
        /// </summary>
            AlchemicForce = 238,

        /// <summary>
        /// Value for the creator ultimate class. Bits: 0b0000_1110_1111
        /// </summary>
            Creator = 239,

        /// <summary>
        /// Value for the crusader character class. Bits: 0b0000_1111_0000
        /// </summary>
            Crusader = 240,

        /// <summary>
        /// Value for the impact crusader advanced class. Bits: 0b0000_1111_1000
        /// </summary>
            ImpactCrusader = 248,

        /// <summary>
        /// Value for the master paladin advanced class. Bits: 0b0000_1111_1100
        /// </summary>
            MasterPaladin = 252,

        /// <summary>
        /// Value for the sacred paladin elite class. Bits: 0b0000_1111_1110
        /// </summary>
            SacredPaladin = 254,

        /// <summary>
        /// Value for the templar commander ultimate class. Bits: 0b0000_1111_1111
        /// </summary>
            TemplarCommander = 255,
    }

    /// <summary>
    /// Defines the type of a character stat attribute.
    /// </summary>
    public enum CharacterStatAttribute
    {
        /// <summary>
        /// The strength attribute.
        /// </summary>
            Strength = 0,

        /// <summary>
        /// The agility attribute.
        /// </summary>
            Agility = 1,

        /// <summary>
        /// The vitality attribute.
        /// </summary>
            Vitality = 2,

        /// <summary>
        /// The energy attribute.
        /// </summary>
            Energy = 3,

        /// <summary>
        /// The leadership attribute.
        /// </summary>
            Leadership = 4,
    }

    /// <summary>
    /// Defines the hero state of a character.
    /// </summary>
    public enum CharacterHeroState
    {
        /// <summary>
        /// The character is new and has the highest state.
        /// </summary>
            New = 0,

        /// <summary>
        /// The character is a hero.
        /// </summary>
            Hero = 1,

        /// <summary>
        /// The character is a hero, but the state is almost gone.
        /// </summary>
            LightHero = 2,

        /// <summary>
        /// The character is in a neutral state.
        /// </summary>
            Normal = 3,

        /// <summary>
        /// The character killed another character, and has a kill warning.
        /// </summary>
            PlayerKillWarning = 4,

        /// <summary>
        /// The character killed two characters, and has some restrictions.
        /// </summary>
            PlayerKiller1stStage = 5,

        /// <summary>
        /// The character killed more than two characters, and has hard restrictions.
        /// </summary>
            PlayerKiller2ndStage = 6,
    }

    /// <summary>
    /// Describes the way how the player wants to leave the current game.
    /// </summary>
    public enum LogOutType
    {
        /// <summary>
        /// The player wants to close the game.
        /// </summary>
            CloseGame = 0,

        /// <summary>
        /// The player wants to go back to the character selection screen.
        /// </summary>
            BackToCharacterSelection = 1,

        /// <summary>
        /// The player wants to go back to the server selection screen.
        /// </summary>
            BackToServerSelection = 2,
    }

    /// <summary>
    /// Defines the type of the mini game.
    /// </summary>
    public enum MiniGameType
    {
        /// <summary>
        /// Undefined mini game type.
        /// </summary>
            Undefined = 0,

        /// <summary>
        /// The devil square mini game.
        /// </summary>
            DevilSquare = 1,

        /// <summary>
        /// The blood castle mini game.
        /// </summary>
            BloodCastle = 2,

        /// <summary>
        /// The cursed temple mini game.
        /// </summary>
            CursedTemple = 3,

        /// <summary>
        /// The chaos castle mini game.
        /// </summary>
            ChaosCastle = 4,

        /// <summary>
        /// The illusion temple mini game.
        /// </summary>
            IllusionTemple = 5,

        /// <summary>
        /// The doppelgänger mini game.
        /// </summary>
            Doppelganger = 6,
    }

